### ISSUE TITLE
How to change to SQL Server?

### ISSUE THREAD

**Issue by life-dev-test** [odemur/spring-boot-rest-api#1]

**Comment by odemur** [comment]
Hello, 

You can use this:
 
# SQL Server Database Configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=customer
spring.datasource.username=your_sql_server_username
spring.datasource.password=your_sql_server_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
